### ISSUE TITLE
LibUV tutorial: output goes through `stderr`

### ISSUE THREAD

**Issue by nanotee** [jamestthompson3/dank#7]
Hi! Not sure if this is the right place to report this, but I believe there's a slight mistake in the article "Using LibUV in Neovim":

```lua
  handle = vim.loop.spawn('rg', {
    args = {term, '--vimgrep', '--smart-case'},
    stdio = {stdout,stderr}
  },
```

I think stdio has to be `{nil, stdout, stderr}`, in that order, otherwise the output goes through the `stderr` pipe. You can test this by commenting out `vim.loop.read_start(stdout, onread)`: the script still works.

Thanks for making that kind of info available by the way! Having a high-level tutorial definitely helps to get started

**Comment by nanotee** [comment]
Oops, just noticed nobody's watching the repository, ping @jamestthompson3

**Comment by jamestthompson3** [comment]
Thanks for calling this out! I'll fix this in the posts!

**Comment by jamestthompson3** [comment]
pushed an edit. Thanks again for calling this out. I also appreciate the traffic that your nvim-lua-guide drives to my site. FWIW, I redesigned the blog to be a bit more readable, and the new URL for this post you reference is at https://teukka.tech/posts/2020-01-07-vimloop/, of course the old page will still work as well :)

**Comment by nanotee** [comment]
Fantastic, I'll update the URL. Thanks for the quick fix!
